services:
  doc_page_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: doc_page_backend
    ports:
      - "3333:3333"
    restart: always

  doc_page_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: doc_page_frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - doc_page_backend